apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This will overwrite the namespace; all resources will be deployed to the specified namespace
namespace: vault

resources:
- ../../base

patches:
- path: namespace.yaml

# List the Helm chart we want to deploy
helmCharts:
- name: vault
  namespace: vault
  repo: https://helm.releases.hashicorp.com
  releaseName: vault
  version: 0.28.1
  valuesFile: values.yaml

secretGenerator:
- name: vault-kms
  env: .env

generatorOptions:
  disableNameSuffixHash: true
