apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-tooling
resources:
- ../../base
- namespace.yaml
- service-account.yaml

commonLabels:
  env: dev-tooling

patches:
- path: deployment.yaml
