apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooling-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tooling
    spec:
      containers:
      - name: tooling
        image: steghub/tooling-app:1.0.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        env:
        - name: DB_HOST
          value: "db-endpoint"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "tooling_db"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: aurora-db-credentials
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aurora-db-credentials
              key: DB_PASSWORD
